### ISSUE TITLE
Long lived http connections are bad

### ISSUE THREAD

**Issue by petemoore** [taskcluster/taskcluster-queue#238]
The queue should not be holding http connections for 20 seconds in `claimWork` calls as per https://github.com/taskcluster/taskcluster-queue/blob/ccac868c7944e233cbf76f0d9bc7c52271cc9145/src/api.js#L1384. It looks like this idea was introduced in PR #146.

The problems I see with this approach are:

1) The server has to maintain a large number of concurrent http connections with a large number of clients. Imagine all workers poll claimWork every 10s - this would mean that the queue would maintain active http connections to every single worker at a given point in time.
2) It increases pending time for workers - imagine a new worker is spawned to execute a task. When the worker starts up, it has to wait at least 20 seconds for the claimWork call to complete, before it can claim the task. If the 20s delay was not implemented in the queue, it would start the task 20s sooner.

The better place to implement the wait is on the worker between http requests, and to configure throttling on the web front ends (e.g. in [CloudFront](http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html)).

**Comment by jonasfj** [comment]
1. yes, this is by design, we do long polling.
2. no, workers have to wait at-most 20s for claimWork to return.

Note. Inside the queue it is constantly polling for tasks as long as there is a long-polling connection.

This was implemented a long time ago... I am happy to go over the details :)  I'm pretty sure we had very wide consensus for polling through the queue..

I think you're misreading the at-least 20 seconds part :)

**Comment by petemoore** [comment]
I was misreading, you're right! That changes things a lot - and actually means an improvement in wait times.

And after researching long polling, I see this is an accepted mechanism these days - so maybe my concerns about maintaining so many active connections is not such a problem.
